version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
